/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login.form;

/**
 *
 * @author Kelly Meyer
 */
public class Grades extends javax.swing.JFrame {

    /**
     * Creates new form Grades
     */
    public Grades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jlabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        GradesPerModule = new javax.swing.JRadioButton();
        Modules = new javax.swing.JRadioButton();
        FinalGrade = new javax.swing.JRadioButton();
        Back = new javax.swing.JButton();
        View = new javax.swing.JButton();
        modulecodeA = new javax.swing.JLabel();
        modulecodeB = new javax.swing.JLabel();
        modulecodeC = new javax.swing.JLabel();
        modulecodeD = new javax.swing.JLabel();
        modulenameA = new javax.swing.JLabel();
        modulenameB = new javax.swing.JLabel();
        modulenameC = new javax.swing.JLabel();
        modulenameD = new javax.swing.JLabel();
        FA1_1 = new javax.swing.JLabel();
        FA1_2 = new javax.swing.JLabel();
        FA1_3 = new javax.swing.JLabel();
        FA1_4 = new javax.swing.JLabel();
        FA2_1 = new javax.swing.JLabel();
        FA2_2 = new javax.swing.JLabel();
        FA2_3 = new javax.swing.JLabel();
        FA2_4 = new javax.swing.JLabel();
        SA1_1 = new javax.swing.JLabel();
        SA1_2 = new javax.swing.JLabel();
        SA1_3 = new javax.swing.JLabel();
        SA1_4 = new javax.swing.JLabel();
        SA2_1 = new javax.swing.JLabel();
        SA2_2 = new javax.swing.JLabel();
        SA2_3 = new javax.swing.JLabel();
        SA2_4 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grades");
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 0, 0));

        jlabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(204, 0, 0));
        jlabel1.setText("     Calculate Grades");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Module code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Module name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("FA1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("FA2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("SA1");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("SA2");

        GradesPerModule.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GradesPerModule.setForeground(new java.awt.Color(153, 0, 0));
        GradesPerModule.setText("Grades Per Module");
        GradesPerModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradesPerModuleActionPerformed(evt);
            }
        });

        Modules.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Modules.setForeground(new java.awt.Color(153, 0, 0));
        Modules.setText("Modules");
        Modules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulesActionPerformed(evt);
            }
        });

        FinalGrade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FinalGrade.setForeground(new java.awt.Color(153, 0, 0));
        FinalGrade.setText("Final Grade");
        FinalGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalGradeActionPerformed(evt);
            }
        });

        Back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Back.setForeground(new java.awt.Color(153, 0, 0));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        View.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        View.setForeground(new java.awt.Color(153, 0, 0));
        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        modulecodeA.setText("HTSS1171");

        modulecodeB.setText("HBFB1161");

        modulecodeC.setText("HBCM1161");

        modulecodeD.setText("HPRX1161");

        modulenameA.setText("Technical Systems and Support 1");

        modulenameB.setText("Basic Finance and Budgeting 1");

        modulenameC.setText("Business Communications 1");

        modulenameD.setText("Praxis 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modulecodeA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulecodeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulecodeC, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(modulecodeD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(814, 814, 814)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SA2_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(SA2_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SA2_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SA2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(205, 205, 205)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                            .addComponent(FA1_1)
                                            .addComponent(FA1_2)
                                            .addComponent(FA1_3)
                                            .addComponent(FA1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(104, 104, 104)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(FA2_1)
                                            .addComponent(FA2_2)
                                            .addComponent(FA2_3)
                                            .addComponent(FA2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(82, 82, 82)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addComponent(SA1_1)
                                            .addComponent(SA1_2)
                                            .addComponent(SA1_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(SA1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(89, 89, 89))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(modulenameD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(modulenameC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(modulenameA, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                                    .addComponent(modulenameB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Modules)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(GradesPerModule)
                                                .addGap(117, 117, 117)
                                                .addComponent(FinalGrade)
                                                .addGap(113, 113, 113))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Back)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(View)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SA2_1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(SA1_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FA2_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulenameA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulecodeA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FA1_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SA2_2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(SA1_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FA2_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulenameB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulecodeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FA1_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SA2_3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(SA1_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FA2_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FA1_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulenameC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulecodeC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FA2_4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(modulecodeD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modulenameD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FA1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SA1_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SA2_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Back)
                    .addComponent(Modules)
                    .addComponent(GradesPerModule)
                    .addComponent(FinalGrade)
                    .addComponent(View))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalGradeActionPerformed
        // TODO add your handling code here:
        Modules.setSelected(false);
        GradesPerModule.setSelected(false);
        FinalGrade.setSelected(true);


    }//GEN-LAST:event_FinalGradeActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        frmMain frm = new frmMain();
        frm.pack();
        frm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BackActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
        
            modulecodeA.setText("HTSS1171");
            modulecodeB.setText("HBFB1161");
            modulecodeC.setText("HBCM1161");
            modulecodeD.setText("HPRX1161");
            
            modulenameA.setText ("Technical Systems and Support 1");
            modulenameB.setText ("Basic Finance and Budgeting 1");
            modulenameC.setText ("Business Communications 1");
            modulenameD.setText ("Praxis 1");

            if(Modules.isSelected())
        {
         FA1_1.setText("");        
         FA1_2.setText("");
         FA1_3.setText("");
         FA1_4.setText("");
        
         FA2_1.setText("");
         FA2_2.setText("");
         FA2_3.setText("");
         FA2_4.setText("");
         
         SA1_1.setText("");
         SA1_2.setText("");
         SA1_3.setText("");
         SA1_4.setText("");
         
         SA2_1.setText("");
         SA2_2.setText("");
         SA2_3.setText("");
         SA2_4.setText("");     
                    
            
          
        }
        if(GradesPerModule.isSelected())
        {         
         
         FA1_1.setText(String.valueOf(81*100/20));
         FA1_2.setText(String.valueOf(75*100/20));
         FA1_3.setText(String.valueOf(68*100/20));
         FA1_4.setText(String.valueOf(74*100/20));
        
         FA2_1.setText(String.valueOf(35*50/20));
         FA2_2.setText(String.valueOf(42*50/20));
         FA2_3.setText(String.valueOf(50*50/20));
         FA2_4.setText(String.valueOf(45*50/20));
         
         SA1_1.setText(String.valueOf(52*70/50));
         SA1_2.setText(String.valueOf(64*70/50));
         SA1_3.setText(String.valueOf(55*70/50));
         SA1_4.setText(String.valueOf(68*70/50));
         
         SA2_1.setText(String.valueOf(14*20/10));
         SA2_2.setText(String.valueOf(16*20/10));
         SA2_3.setText(String.valueOf(18*20/10));
         SA2_4.setText(String.valueOf(15*20/10));     
        }
        if(FinalGrade.isSelected())
        {
         FA1_1.setText("81/100");
         FA1_2.setText("75/100");
         FA1_3.setText("68/100");
         FA1_4.setText("74/100");
        
         FA2_1.setText("35/50");
         FA2_2.setText("42/50");
         FA2_3.setText("50/50");
         FA2_4.setText("45/50");
         
         SA1_1.setText("52/70");
         SA1_2.setText("64/70");
         SA1_3.setText("55/70");
         SA1_4.setText("68/70");
         
         SA2_1.setText("14/20");
         SA2_2.setText("16/20");
         SA2_3.setText("18/20");
         SA2_4.setText("15/20");
        }

    }//GEN-LAST:event_ViewActionPerformed

    private void ModulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulesActionPerformed
        // TODO add your handling code here:
        Modules.setSelected(true);
        GradesPerModule.setSelected(false);
        FinalGrade.setSelected(false);

    }//GEN-LAST:event_ModulesActionPerformed

    private void GradesPerModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesPerModuleActionPerformed
        // TODO add your handling code here:
        Modules.setSelected(false);
        GradesPerModule.setSelected(true);
        FinalGrade.setSelected(false);
    }//GEN-LAST:event_GradesPerModuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grades().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel FA1_1;
    private javax.swing.JLabel FA1_2;
    private javax.swing.JLabel FA1_3;
    private javax.swing.JLabel FA1_4;
    private javax.swing.JLabel FA2_1;
    private javax.swing.JLabel FA2_2;
    private javax.swing.JLabel FA2_3;
    private javax.swing.JLabel FA2_4;
    private javax.swing.JRadioButton FinalGrade;
    private javax.swing.JRadioButton GradesPerModule;
    private javax.swing.JRadioButton Modules;
    private javax.swing.JLabel SA1_1;
    private javax.swing.JLabel SA1_2;
    private javax.swing.JLabel SA1_3;
    private javax.swing.JLabel SA1_4;
    private javax.swing.JLabel SA2_1;
    private javax.swing.JLabel SA2_2;
    private javax.swing.JLabel SA2_3;
    private javax.swing.JLabel SA2_4;
    private javax.swing.JButton View;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel modulecodeA;
    private javax.swing.JLabel modulecodeB;
    private javax.swing.JLabel modulecodeC;
    private javax.swing.JLabel modulecodeD;
    private javax.swing.JLabel modulenameA;
    private javax.swing.JLabel modulenameB;
    private javax.swing.JLabel modulenameC;
    private javax.swing.JLabel modulenameD;
    // End of variables declaration//GEN-END:variables
}
